// here will be all types, for example: export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
// export const ADD_TO_BUY_ARR = "ADD_TO_BUY_ARR";
// export const SAVE_BUY_ARR_TO_LOCALE_STORAGE = "SAVE_BUY_ARR_TO_LOCAL_STORAGE";

export const UPDATE_USER_DATA_USERNAME = "UPDATE_USER_DATA_USERNAME";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_REMEMBER_ME_ACTION = "UPDATE_REMEMBER_ME_ACTION";
