export const UPDATE_USER_DATA_USERNAME = "UPDATE_USER_DATA_USERNAME";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_REMEMBER_ME_ACTION = "UPDATE_REMEMBER_ME_ACTION";

export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN";
export const SET_USER_ID = "SET_USER_ID";
export const SET_USER_DATA = "SET_USER_DATA"
export const SET_SEARCH_ID = "SET_SEARCH_ID"
export const SET_SEARCH_DATA = "SET_SEARCH_DATA"
export const SET_USER_FOLLOW = "SET_USER_FOLLOW"
export const SET_USER_UNFOLLOW = "SET_USER_UNFOLLOW"
export const SET_SEARCH_USER_FOLLOW = "SET_SEARCH_USER_FOLLOW"
export const SET_SEARCH_USER_UNFOLLOW = "SET_SEARCH_USER_UNFOLLOW"
export const SET_USER_FOLLOWING = "SET_USER_FOLLOWING"
export const SET_POSTS = "SET_POSTS";
export const SET_USER_POST = "SET_USER_POST";
export const SET_PAGE = "SET_PAGE";
export const SET_CLEAR_POSTS = "SET_CLEAR_POSTS";
export const ADD_EXPLORE_POSTS = "ADD_EXPLORE_POSTS";
export const ADD_REGISTRATION_POSTS = "ADD_REGISTRATION_POSTS";

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";
export const OPEN_SIGN_UP_MODAL = "OPEN_SIGN_UP_MODAL";
export const CLOSE_SIGN_UP_MODAL = "CLOSE_SIGN_UP_MODAL";
export const OPEN_EDIT_MODAL = "OPEN_EDIT_MODAL";
export const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL";

export const SET_STEP_MODAL = "SET_STEP_MODAL";
export const SET_VALUE_MODAL = "SET_VALUE_MODAL";
export const NEW_USER_DATA_FIRST_STEP_REGISTRATION = "NEW_USER_DATA_FIRST_STEP_REGISTRATION";
export const step4 = "step4";

export const CHECK_EMAIL = "CHECK_EMAIL";
export const CODE_CHECK = "CODE_CHECK";
export const NEW_PASSWORD = "NEW_PASSWORD";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const SET_PROFILE_POSTS = "SET_PROFILE_POSTS"
export const SET_PROFILE_LIKE_POSTS = "SET_PROFILE_LIKE_POSTS"
export const SET_PROFILE_REPOSTS = "SET_PROFILE_REPOSTS"

export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS"
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS"
export const SET_INBOX = "SET_INBOX"
export const SET_USER_MODE = "SET_USER_MODE"