// here will be all types, for example: export const PRODUCTS_LOAD = "PRODUCTS_LOAD";
// export const ADD_TO_BUY_ARR = "ADD_TO_BUY_ARR";
// export const SAVE_BUY_ARR_TO_LOCALE_STORAGE = "SAVE_BUY_ARR_TO_LOCAL_STORAGE";

export const UPDATE_USER_DATA_USERNAME = "UPDATE_USER_DATA_USERNAME";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";
export const UPDATE_REMEMBER_ME_ACTION = "UPDATE_REMEMBER_ME_ACTION";

export const SAVE_USER_TOKEN = "SAVE_USER_TOKEN"

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL'
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL'
export const OPEN_SIGN_UP_MODAL = 'OPEN_SIGN_UP_MODAL'
export const CLOSE_SIGN_UP_MODAL = 'CLOSE_SIGN_UP_MODAL'

export const SET_STEP_MODAL = "SET_STEP_MODAL";
export const SET_VALUE_MODAL = "SET_VALUE_MODAL";
export const NEW_USER_DATA_FIRST_STEP_REGISTRATION = "NEW_USER_DATA_FIRST_STEP_REGISTRATION";
export const step4 = "step4";