name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.0-jammy
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Set up JDK 17'
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    - name: 'Set up Maven'
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.1
    - name: 'Cache Maven packages'
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: 'Prepare .env for API'
      working-directory: social_network_api
      run: |
        echo "SERVER_PORT=8080\n
              SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}\n
              SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}\n
              SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}\n
              SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}\n
              SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}\n
              SPRING_MAIL_HOST=${{ secrets.SPRING_MAIL_HOST }}\n
              SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}\n
              SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}" > .env
    - name: 'Build API'
      working-directory: social_network_api
      run: mvn install
    - name: 'Cache node modules'
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: 'Install dependencies (UI)'
      working-directory: social-network-ui
      run: npm ci
    - name: 'Install dependencies (E2E)'
      working-directory: e2e
      run: npm ci
    - name: 'Run E2E tests'
      working-directory: e2e
      run: npm test
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
